/*
 * Waiting List Api
 *
 * Ambulance Waiting List API
 *
 * API version: 1.0.3
 * Contact: xmartinkao@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package oma_wac_certs

type User struct {

	// The user ID
	Id string `json:"id"`

	// The user name
	Name string `json:"name"`

	Certifications []UserCertification `json:"certifications"`
}
