/*
 * Waiting List Api
 *
 * Ambulance Waiting List API
 *
 * API version: 1.0.3
 * Contact: xmartinkao@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package oma_wac_certs

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newAmbulanceStaffCertificationsAPI()
    api.addRoutes(group)
  }
  
}
