kind: Service
apiVersion: v1
metadata:
  name: oma-ambulance-certs-webapi
spec:
  selector:
    pod: oma-ambulance-certs-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port
